server:
  port: 8081

keycloak:
  realm-url: http://localhost:8080/realms/SpringBootKeycloak
  client-id: spring-app
  user-name-attribute: preferred_username
  authorization-grant-type: authorization_code
  token-url: ${keycloak.realm-url}/protocol/openid-connect/token
  logout-url: ${keycloak.realm-url}/protocol/openid-connect/logout

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${keycloak.realm-url}
            user-name-attribute: ${keycloak.user-name-attribute}
        registration:
          keycloak:
            client-id: ${keycloak.client-id}
            authorization-grant-type: ${keycloak.authorization-grant-type}
            scope: openid
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.realm-url}
          jwk-set-uri: ${keycloak.realm-url}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: ${keycloak.client-id}
      principle-attribute: ${keycloak.user-name-attribute}

logging:
  level:
    org.springframework.security: debug
